### ISSUE TITLE
Relative path

### ISSUE THREAD

**Issue by samuelhaeussler** [mratmeyer/rsslookup#3]
Relative paths aren't discovered correctly.
https://example.com/blog/ with the following RSS in head:
<link rel='alternate' type='application/rss+xml' title='Feed' href='feed/'>
Is discovered as https://example.com/feed/ instead of /blog/feed/

**Comment by samuelhaeussler** [comment]
Sure, here an example: https://sam.uber.space/blog/

**Comment by mratmeyer** [comment]
I've pushed a change that simplifies the logic for parsing relative paths, which takes care of this case and others as well. Thanks for the heads up!
